### ISSUE TITLE
showing error 

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [mukeshsolanki/App-Runtime-Permissions-Android#3]
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
on this line
-->   if (grantResults[0] == PackageManager.PERMISSION_DENIED) {
                    Toast.makeText(this, "Storage Permissions not granted", Toast.LENGTH_SHORT).show();
                } else {
                    Toast.makeText(this, "Storage Permissions granted", Toast.LENGTH_SHORT).show();
                }

**Comment by mukeshsolanki** [comment]
This is an error the user has to handle does not require a change on the library you can handle it by a simple check like wise

```
if(grantResults!=null && grantResults.length()==0){
     return;
}
```
